export type RootStackParamList = {
  Splash: undefined;
  Welcome: undefined;
  Onboarding: undefined;
  MainTabs: undefined;
  Home: undefined;
  JournalHome: undefined;
  JournalReview: undefined;
  DailyEntry: { section?: 'gratitude' | 'evening'; date?: string };
  Affirmations: undefined;
  AffirmationLoop: { affirmations: string[]; duration: number };
  VisionBoard: undefined;
  EditAffirmations: undefined;
  EditMorningRoutine: undefined;
  EditEveningRoutine: undefined;
  EditGoals: undefined;
  EditTraits: undefined;
  EditStandards: undefined;
  EditReminders: undefined;
  EditDailyHabits: undefined;
  EditVisionBoard: { category?: 'roleModels' | 'lifestyle' | 'bodyGoals' | 'successSymbols' | 'inspiration' };
  ViewJournal: undefined;
  VisionBoardSlideshow: undefined;
  Settings: undefined;
  StreakHistory: undefined;
};
